development:
  adapter: postgresql
  database: bookl_development
  pool: 5
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: bookl_test
  host: localhost
  pool: 5
  username: postgres
  password: password