development:
  adapter: postgresql
  database: bookl_development
  pool: 5
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookl_test
  host: localhost
  pool: 5
  username:
  password: